tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "on-surface": "#191c1d",
        "surface-variant": "#e1e3e4",
        "secondary-fixed-dim": "#fabd00",
        "on-tertiary": "#ffffff",
        "surface-container": "#edeeef",
        "secondary": "#785900",
        "on-secondary-container": "#6c5000",
        "outline-variant": "#c5c6d2",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-background": "#191c1d",
        "primary-fixed-dim": "#b3c5ff",
        "on-primary-container": "#758dd5",
        "surface": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "tertiary": "#2d0700",
        "surface-container-highest": "#e1e3e4",
        "tertiary-container": "#501300",
        "primary-container": "#002366",
        "on-primary-fixed-variant": "#2a4386",
        "surface-container-high": "#e7e8e9",
        "inverse-primary": "#b3c5ff",
        "secondary-fixed": "#ffdf9e",
        "surface-tint": "#435b9f",
        "on-error": "#ffffff",
        "secondary-container": "#fdc003",
        "inverse-surface": "#2e3132",
        "on-tertiary-fixed-variant": "#783018",
        "background": "#f8f9fa",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-fixed-variant": "#5b4300",
        "on-tertiary-container": "#d37758",
        "outline": "#757682",
        "error": "#ba1a1a",
        "primary": "#00113a",
        "surface-container-low": "#f3f4f5",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#261a00",
        "surface-bright": "#f8f9fa",
        "tertiary-fixed": "#ffdbd0",
        "on-primary-fixed": "#00174a",
        "on-tertiary-fixed": "#390b00",
        "on-surface-variant": "#444650",
        "tertiary-fixed-dim": "#ffb59e"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
}